apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama3-api
  template:
    metadata:
      labels:
        app: llama3-api
    spec:
      containers:
      - name: llama3-api-container
        image: llama3-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: llama3-api-service
spec:
  selector:
    app: llama3-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
